package com.aaa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-02T19:07:51.496+09:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.aaa.com", name = "ISearchPort")
@XmlSeeAlso({ObjectFactory.class})
public interface ISearchPort {

    @WebMethod
    @RequestWrapper(localName = "setShopItems", targetNamespace = "http://www.aaa.com", className = "com.aaa.SetShopItems")
    @ResponseWrapper(localName = "setShopItemsResponse", targetNamespace = "http://www.aaa.com", className = "com.aaa.SetShopItemsResponse")
    public void setShopItems(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getProductsInfo", targetNamespace = "http://www.aaa.com", className = "com.aaa.GetProductsInfo")
    @ResponseWrapper(localName = "getProductsInfoResponse", targetNamespace = "http://www.aaa.com", className = "com.aaa.GetProductsInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.aaa.GetProductsInfoResponse.Return getProductsInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
