package com.aaa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-02T19:07:51.542+09:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "SearchBeanService", 
                  wsdlLocation = "http://localhost:8080/SOAPSearchItemWeb/SearchBean?wsdl",
                  targetNamespace = "http://www.aaa.com") 
public class SearchBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.aaa.com", "SearchBeanService");
    public final static QName SearchBeanPort = new QName("http://www.aaa.com", "SearchBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPSearchItemWeb/SearchBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SearchBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPSearchItemWeb/SearchBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SearchBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SearchBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SearchBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SearchBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SearchBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ISearchPort
     */
    @WebEndpoint(name = "SearchBeanPort")
    public ISearchPort getSearchBeanPort() {
        return super.getPort(SearchBeanPort, ISearchPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISearchPort
     */
    @WebEndpoint(name = "SearchBeanPort")
    public ISearchPort getSearchBeanPort(WebServiceFeature... features) {
        return super.getPort(SearchBeanPort, ISearchPort.class, features);
    }

}
