package com.aaa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-27T19:55:35.156+09:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "CallMemberBeanService", 
                  wsdlLocation = "http://localhost:8080/SOAPJaxbWeb/CallMemberBean?wsdl",
                  targetNamespace = "http://www.aaa.com") 
public class CallMemberBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.aaa.com", "CallMemberBeanService");
    public final static QName CallMemberBeanPort = new QName("http://www.aaa.com", "CallMemberBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPJaxbWeb/CallMemberBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CallMemberBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPJaxbWeb/CallMemberBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CallMemberBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CallMemberBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CallMemberBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CallMemberBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CallMemberBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CallMemberBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ICallMemberPort
     */
    @WebEndpoint(name = "CallMemberBeanPort")
    public ICallMemberPort getCallMemberBeanPort() {
        return super.getPort(CallMemberBeanPort, ICallMemberPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICallMemberPort
     */
    @WebEndpoint(name = "CallMemberBeanPort")
    public ICallMemberPort getCallMemberBeanPort(WebServiceFeature... features) {
        return super.getPort(CallMemberBeanPort, ICallMemberPort.class, features);
    }

}
