package com.aaa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-27T19:55:35.127+09:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.aaa.com", name = "ICallMemberPort")
@XmlSeeAlso({ObjectFactory.class})
public interface ICallMemberPort {

    @WebMethod
    @RequestWrapper(localName = "getMember", targetNamespace = "http://www.aaa.com", className = "com.aaa.GetMember")
    @ResponseWrapper(localName = "getMemberResponse", targetNamespace = "http://www.aaa.com", className = "com.aaa.GetMemberResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.aaa.GetMemberResponse.Return getMember(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
