package com.aaa.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-02T08:27:09.281+09:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://soap.aaa.com/", name = "ILoginPort")
@XmlSeeAlso({ObjectFactory.class})
public interface ILoginPort {

    @WebMethod
    @RequestWrapper(localName = "loginFunc", targetNamespace = "http://soap.aaa.com/", className = "com.aaa.soap.LoginFunc")
    @ResponseWrapper(localName = "loginFuncResponse", targetNamespace = "http://soap.aaa.com/", className = "com.aaa.soap.LoginFuncResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String loginFunc(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
