package com.aaa.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-02T08:27:09.393+09:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "LoginBeanService", 
                  wsdlLocation = "http://localhost:8080/SOAPLoginWeb/LoginBean?wsdl",
                  targetNamespace = "http://soap.aaa.com/") 
public class LoginBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.aaa.com/", "LoginBeanService");
    public final static QName LoginBeanPort = new QName("http://soap.aaa.com/", "LoginBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPLoginWeb/LoginBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPLoginWeb/LoginBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoginBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LoginBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LoginBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LoginBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ILoginPort
     */
    @WebEndpoint(name = "LoginBeanPort")
    public ILoginPort getLoginBeanPort() {
        return super.getPort(LoginBeanPort, ILoginPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILoginPort
     */
    @WebEndpoint(name = "LoginBeanPort")
    public ILoginPort getLoginBeanPort(WebServiceFeature... features) {
        return super.getPort(LoginBeanPort, ILoginPort.class, features);
    }

}
