
package com.aaa.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Fri Mar 02 07:55:32 KST 2018
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "loginFunc", namespace = "http://soap.aaa.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loginFunc", namespace = "http://soap.aaa.com/", propOrder = {"arg0", "arg1"})

public class LoginFunc {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

}

