
package com.aaa.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Fri Mar 02 07:55:32 KST 2018
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "loginFuncResponse", namespace = "http://soap.aaa.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loginFuncResponse", namespace = "http://soap.aaa.com/")

public class LoginFuncResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

