
package com.aaa.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Tue Feb 27 19:23:45 KST 2018
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "getMemberResponse", namespace = "http://www.aaa.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMemberResponse", namespace = "http://www.aaa.com")

public class GetMemberResponse {

    @XmlElement(name = "return")
    private com.aaa.soap.Member _return;

    public com.aaa.soap.Member getReturn() {
        return this._return;
    }

    public void setReturn(com.aaa.soap.Member new_return)  {
        this._return = new_return;
    }

}

