
package com.aaa.soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Tue Feb 27 19:23:45 KST 2018
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "getMember", namespace = "http://www.aaa.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMember", namespace = "http://www.aaa.com")

public class GetMember {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

