package com.aaa.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-02-25T19:09:50.542+09:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://soap.aaa.com/", name = "ISayHelloPort")
@XmlSeeAlso({ObjectFactory.class})
public interface ISayHelloPort {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.aaa.com/", className = "com.aaa.soap.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.aaa.com/", className = "com.aaa.soap.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
